@rootUrl=http://localhost:8000

#API list

### Check server status
Get {{rootUrl}}

### Auth API

### Post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName": "Kovid",
    "lName": "Kunduru",
    "email": "a3@a.com",
    "phone": "017576789",
    "password": "Roh@123"
    
}
### Post to activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId": "67cce6ecfb70492ecd5a52a1",
    "t": "bfb1ea3b-9a0c-42aa-abf9"
    
}

### Login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "a2@a.com",
    "password": "Roh@123"
    
}
### Get user's profile
GET  {{rootUrl}}/api/v1/user/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzQyNDQ1NTg0LCJleHAiOjE3NDI0NDY0ODR9.XMakYjxnvrkKvhfPq2KbO31v6DU5zMmN-ARy8rWSvC8


### Renew AccessJWT 
GET  {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzQyNDQ1NTM4LCJleHAiOjE3NDUwMzc1Mzh9.JWPSDuYa1vxaNF1oAcTscpjZg9SRk2_z_e-2CK3p6pM