@rootUrl=http://localhost:8000

#API list

### Check server status
Get {{rootUrl}}

### Auth API

### Post new user
POST {{rootUrl}}/api/v1/auth/registers
Content-Type: application/json

{
    "fName": "Kovid",
    "lName": "Kunduru",
    "email": "a7@a.com",
    "phone": "017576789",
    "password": "Roh@123"
    
}
### Post to activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId": "6831bcd77b5dc8f1c88f77cd",
    "t": "139e9948-f19d-4006-b4be-7aea783d496c"
    
}

### Login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "a2@a.com",
    "password": "Roh@123-2"
    
}
### Get user's profile
GET  {{rootUrl}}/api/v1/user/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzQ5MDc4NDY4LCJleHAiOjE3NDkwNzkzNjh9.f_M8OzDqy9X9UMTX9e4TqvwuY_-EmX3512nHvL7RKAA


### Renew AccessJWT 
GET  {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzQ2NzE3NTk0LCJleHAiOjE3NDY3MTg0OTR9.fiqQI9PTfj09jvKgRqXEqw5_D3MDVOlWRAy8ZFmyZNk


### OTP Request
POST  {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
    "email" : "a2@a.com"
}

### Reset password
POST  {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
    "email" : "a2@a.com",
    "password" : "Roh@123-2",
    "otp" : 5893
}


#### Book API

### Get single book
GET {{rootUrl}}/api/v1/books/public/clean-architecture1

### Get all books by user (Only active)
GET {{rootUrl}}/api/v1/books

### Get all books by admin (All books, both active and inactive)
GET {{rootUrl}}/api/v1/books/admin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzUxODU3NTE4LCJleHAiOjE3NTE4NTg0MTh9.q653HZ31LiFak_0ukNMKQtErnrZTv4oTJZn7PP3pnJk

### Insert book(s)
POST {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzUxOTQ4NzU3LCJleHAiOjE3NTE5NDk2NTd9.9l300_xta_BKgiR8fdtARtddIzoqnJA96OLxIa-rcmE

{
            "title" : "Javascript the good parts",
            "year" : 2008,
            "author" : "Douglas Crockford",
            "imgUrl" : "https://images-na.ssl-images-amazon.com/images/I/51j2g1v7JmL._SX331_BO1,204,203,200_.jpg",
            "isbn" : "978059680552",
            "genre" : "Programming",
            "description" : "This is a book about the programming language JavaScript. It covers the good parts of JavaScript and how to use them effectively."
            
        
            
      }


### ======= Borrow API
### Insert new borrow 
POST {{rootUrl}}/api/v1/borrows
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzUxOTY1ODIzLCJleHAiOjE3NTE5NjY3MjN9.fbEXfhnBtLxJeBZ4_V6psr0V_Cu1oTAu3rUfcsrIg7Q

[
    {
            "bookTitle" : "Clean Code: A Handbook of Agile Software Craftsmanship",
            "bookId" : "683e9363cebf434e9c6de332",
            
            "thumbnail" : "public/img/1748931465234-773304245-bookImage1.jpg"
            
      }
   
      ]


### Return book
PATCH {{rootUrl}}/api/v1/borrows
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzU3MzM5NzM5LCJleHAiOjE3NTczNDA2Mzl9.k5bn4IkrgKP-BOWPbb36JteBzWgcWtuUgNYSuh_05B4

    {
            
            "_id" : "68b9a11a7a1acb86178a7d5e"
            
            
            
      }

### ======= Reviews
### Post new review
POST {{rootUrl}}/api/v1/reviews
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzU3NDgzNTE4LCJleHAiOjE3NTc0ODQ0MTh9.PUbabxyS3eYQjE8rHtEEKYnU3rK6pPiMKCq4R-0Ucyo

    {
            
             "bookId": "683e9363cebf434e9c6de335",
             "title": "Test review title",
             "reviewMessage": "Awesome book. More to come",
             "rating": 4,
             "borrowId": "68b9a11a7a1acb86178a7d5e"
            
            
            
      }

### Fetch all reviews
GET {{rootUrl}}/api/v1/reviews
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzU4MzM5NDIzLCJleHAiOjE3NTgzNDAzMjN9.ABcYF696hP_-jeVi_8Wj525nGKghs3wgQzeQGnHinMA

### Update review
PATCH {{rootUrl}}/api/v1/reviews/admin
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImEyQGEuY29tIiwiaWF0IjoxNzU5MzI4OTY2LCJleHAiOjE3NTkzMjk4NjZ9.AFfa_cmIXN1W4GNK6WOF4ZTFPW1q8joJe6w4ZP6B76w

{
    "_id" : "68c11221e5eb29978896d8aa",
    "isApproved" : true
}

   
      
